version: '3'
services:
  sender:
    # image: docker.io/ayonnayihan/sample-sendr-rcv-test:sender0.1
    build:
      context: .
      target: sender
    environment:
      SEND_HOST: receiver
      SEND_PORT: 5555
  receiver:
    # image: docker.io/ayonnayihan/sample-sendr-rcv-test:receiver0.1
    build:
      context: .
      target: receiver
    environment:
      LISTEN_HOST: '0.0.0.0' #sender
      LISTEN_PORT: 5555
  # ex3:
  #   build:
  #     context: .
  #     target: ex3
  #   ports: 
  #     - '8080:8080'
